name: just_ui
description: "A lightweight and utilitarian UI package for Flutter, focused on business applications."
version: 0.0.1-alpha.1
homepage: https://github.com/playbott/flutter_just_ui

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
